# Text Encoding
1.Label Encoding:

In [48]:
#Iris Dataset
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [49]:
iris = load_iris()

In [50]:
iris.data = pd.DataFrame(iris.data, columns = iris.feature_names)

In [51]:
iris.data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [52]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [53]:
y = pd.Categorical.from_codes(iris.target, iris.target_names)#Converting the encoded values to Targeted Values

In [54]:
y

['setosa', 'setosa', 'setosa', 'setosa', 'setosa', ..., 'virginica', 'virginica', 'virginica', 'virginica', 'virginica']
Length: 150
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [55]:
le = LabelEncoder()

In [56]:
y = le.fit_transform(y)

In [57]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data,y,test_size = 0.7)

In [59]:
from sklearn.tree import DecisionTreeClassifier
dcf = DecisionTreeClassifier()

In [60]:
dcf.fit(x_train,y_train)

DecisionTreeClassifier()

In [61]:
dcf.score(x_train,y_train)

1.0

In [62]:
dcf.score(x_test,y_test)

0.9047619047619048

2.One Hot Encoder

In [63]:
iris = load_iris()

In [64]:
iris.data = pd.DataFrame(iris.data,columns = iris.feature_names)

In [65]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [66]:
y = pd.Categorical.from_codes(y,iris.target_names)

In [67]:
y

['setosa', 'setosa', 'setosa', 'setosa', 'setosa', ..., 'virginica', 'virginica', 'virginica', 'virginica', 'virginica']
Length: 150
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [68]:
from sklearn.preprocessing import OneHotEncoder
on = OneHotEncoder()

In [69]:
y_enc = on.fit_transform(y.reshape(-1,1))

In [82]:
y_enc = y_enc.toarray()#Convert from sparse matrix to array

In [85]:
x_train,x_test,y_train,y_test = train_test_split(iris.data , y_enc, test_size = 0.25)

In [86]:
dcf = DecisionTreeClassifier()
dcf.fit(x_train,y_train)

DecisionTreeClassifier()

In [87]:
dcf.score(x_test,y_test)

0.9736842105263158

3.Word Embedding


In [90]:
import gensim
from gensim.models import Word2Vec
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/student/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

# Steps for Word Embedding
## 1.Tokenize to get individual words from sentence
## 2.LoweCase()
## 3. Removing the Stopwards (Uneccesary words)
## 4.Pre processed words are sent to the Word2Vec
### Vector_Size = How many dimension of a vector for each word
### window = How many previous words to refer
### min_count = frequency
### workers = threads

In [104]:
etext = "text for preprocessing and word embedding using Python and Gensim library"
words = nltk.word_tokenize(etext)

In [105]:
processed_words = [word.lower() for word in words if word.isalpha() and word.lower() not in nltk.corpus.stopwords.words()]

In [106]:
nltk.download('stopwords')
processed_words


[nltk_data] Downloading package stopwords to
[nltk_data]     /home/student/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


['text', 'preprocessing', 'word', 'embedding', 'python', 'gensim', 'library']

In [107]:
model = Word2Vec([processed_words],vector_size=100,window = 5,min_count = 1,workers=8)

In [108]:
word = "python"
embed = model.wv[word]

In [109]:
embed

array([ 9.4563962e-05,  3.0773198e-03, -6.8126451e-03, -1.3754654e-03,
        7.6685809e-03,  7.3464094e-03, -3.6732971e-03,  2.6427018e-03,
       -8.3171297e-03,  6.2054861e-03, -4.6373224e-03, -3.1641065e-03,
        9.3113566e-03,  8.7338570e-04,  7.4907029e-03, -6.0740625e-03,
        5.1605068e-03,  9.9228229e-03, -8.4573915e-03, -5.1356913e-03,
       -7.0648370e-03, -4.8626517e-03, -3.7785638e-03, -8.5361991e-03,
        7.9556061e-03, -4.8439382e-03,  8.4236134e-03,  5.2625705e-03,
       -6.5500261e-03,  3.9578713e-03,  5.4701497e-03, -7.4265362e-03,
       -7.4057197e-03, -2.4752307e-03, -8.6257253e-03, -1.5815723e-03,
       -4.0343284e-04,  3.2996845e-03,  1.4418805e-03, -8.8142155e-04,
       -5.5940580e-03,  1.7303658e-03, -8.9737179e-04,  6.7936908e-03,
        3.9735902e-03,  4.5294715e-03,  1.4343059e-03, -2.6998555e-03,
       -4.3668128e-03, -1.0320747e-03,  1.4370275e-03, -2.6460087e-03,
       -7.0737829e-03, -7.8053069e-03, -9.1217868e-03, -5.9351693e-03,
      

In [111]:
!pip install scikit-learn==0.13

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 2.2 MB/s eta 0:00:00m eta 0:00:010:00:010m
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [2276 lines of output]
      Partial import of sklearn during the build process.
      /tmp/pip-install-vafi6rp0/scikit-learn_5bca18a35120402f96686da2d26f4da3/setup.py:55: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.core import setup
      Copying source tree into build/py3k for 2to3 transformation...


      RefactoringTool: No changes to /tmp/pip-install-vafi6rp0/scikit-learn_5bca18a35120402f96686da2d26f4da3/build/py3k/sklearn/feature_extraction/setup.py
      RefactoringTool: No changes to /tmp/pip-install-vafi6rp0/scikit-learn_5bca18a35120402f96686da2d26f4da3/build/py3k/sklearn/feature_extraction/stop_words.py
      RefactoringTool: Refactored /tmp/pip-install-vafi6rp0/scikit-learn_5bca18a35120402f96686da2d26f4da3/build/py3k/sklearn/feature_extraction/text.py
      RefactoringTool: Refactored /tmp/pip-install-vafi6rp0/scikit-learn_5bca18a35120402f96686da2d26f4da3/build/py3k/sklearn/feature_extraction/tests/test_dict_vectorizer.py
      RefactoringTool: Refactored /tmp/pip-install-vafi6rp0/scikit-learn_5bca18a35120402f96686da2d26f4da3/build/py3k/sklearn/feature_extraction/tests/test_feature_hasher.py
      RefactoringTool: No changes to /tmp/pip-install-vafi6rp0/scikit-learn_5bca18a35120402f96686da2d26f4da3/build/py3k/sklearn/feature_extraction/tests/test_image.py
      Refactoring

Failed to build scikit-learn
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
  Running setup.py install for scikit-learn ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for scikit-learn did not run successfully.
  │ exit code: 1
  ╰─> [2276 lines of output]
      Partial import of sklearn during the build process.
      /tmp/pip-install-vafi6rp0/scikit-learn_5bca18a35120402f96686da2d26f4da3/setup.py:55: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.htm

         17 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallObjectWithKeywords(
            |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      INFO: /home/student/.conda/envs/NM21AI036/bin/x86_64-conda-linux-gnu-cc -shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/student/.conda/envs/NM21AI036/lib -Wl,-rpath-link,/home/student/.conda/envs/NM21AI036/lib -L/home/student/.conda/envs/NM21AI036/lib -L/home/student/.conda/envs/NM21AI036/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/student/.conda/envs/NM21AI036/lib -Wl,-rpath-link,/home/student/.conda/envs/NM21AI036/lib -L/home/student/.conda/envs/NM21AI036/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/student/.conda/envs/NM21AI036/lib -Wl,-rpath-link,/home/stud

In [ ]:
! pip uninstall scikit-learn

Found existing installation: scikit-learn 1.2.2
Uninstalling scikit-learn-1.2.2:
  Would remove:
    /home/student/.conda/envs/NM21AI036/lib/python3.9/site-packages/scikit_learn-1.2.2.dist-info/*
    /home/student/.conda/envs/NM21AI036/lib/python3.9/site-packages/scikit_learn.libs/libgomp-a34b3233.so.1.0.0
    /home/student/.conda/envs/NM21AI036/lib/python3.9/site-packages/sklearn/*
Proceed (Y/n)? 

In [ ]:
y


In [ ]:
!pip install scikit-learn